name = "tale"
version = "1.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A static story telling generator"
licences = ["MIT"]
repository = { type = "github", user = "Willyboar", repo = "tale" }
# links = [{ title = "Website", href = "" }]


[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
glint = ">= 1.2.1 and < 2.0.0"
ewe = ">= 2.1.1 and < 3.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
tom = ">= 2.0.0 and < 3.0.0"
handles = ">= 5.0.0 and < 6.0.0"
mork = ">= 1.8.0 and < 2.0.0"
frontmatter = ">= 1.0.1 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
gleescript = ">= 1.5.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
